/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.swing.construtor;

/**
 *
 * @author Aluno
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAfro = new javax.swing.JButton();
        btOriental = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbCor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbOssos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbPeso = new javax.swing.JLabel();
        btSuperHumano = new javax.swing.JButton();
        btHumanoFraquinho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAfro.setText("Vai nascer um Afrodescendente");
        btAfro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAfroActionPerformed(evt);
            }
        });

        btOriental.setText("Vai nascer um Oriental");
        btOriental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrientalActionPerformed(evt);
            }
        });

        jLabel1.setText("Cor da pele:");

        lbCor.setForeground(new java.awt.Color(0, 51, 255));
        lbCor.setText("---");

        jLabel2.setText("Densidade óssea:");

        lbOssos.setForeground(new java.awt.Color(23, 2, 12));
        lbOssos.setText("---");

        jLabel3.setText("Peso médio (kg):");

        lbPeso.setForeground(new java.awt.Color(23, 2, 12));
        lbPeso.setText("---");

        btSuperHumano.setText("Vai nascer um Super humano");
        btSuperHumano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuperHumanoActionPerformed(evt);
            }
        });

        btHumanoFraquinho.setText("Vai nascer um Humano Franquinho");
        btHumanoFraquinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHumanoFraquinhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(lbCor))
                    .addComponent(btSuperHumano)
                    .addComponent(btHumanoFraquinho)
                    .addComponent(btOriental)
                    .addComponent(btAfro)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lbOssos))
                            .addComponent(lbPeso))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btAfro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btOriental)
                .addGap(18, 18, 18)
                .addComponent(btSuperHumano)
                .addGap(13, 13, 13)
                .addComponent(btHumanoFraquinho)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbCor))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbOssos)
                        .addGap(18, 18, 18)
                        .addComponent(lbPeso))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOrientalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrientalActionPerformed
        PessoaOriental oriental
                = new PessoaOriental();

        lbCor.setText(oriental.getCor());
        lbOssos.setText(oriental.getDensidadeOssea());
        lbPeso.setText(oriental.getPesoMedio().toString());        // TODO add your handling code here:
    }//GEN-LAST:event_btOrientalActionPerformed

    private void btAfroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAfroActionPerformed

        PessoaAfrodescendente afrodescendente
                = new PessoaAfrodescendente();

        lbCor.setText(afrodescendente.getCor());
        lbOssos.setText(afrodescendente.getDensidadeOssea());
        lbPeso.setText(afrodescendente.getPesoMedio().toString());

    }//GEN-LAST:event_btAfroActionPerformed

    private void btSuperHumanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuperHumanoActionPerformed
        PessoaTransgenica pessoa = new PessoaTransgenica("automático", "iniquebrável", 4.0);
        lbCor.setText(pessoa.getCor());
        lbOssos.setText(pessoa.getDensidadeOssea());
        lbPeso.setText(pessoa.getPesoMedio().toString());
    }//GEN-LAST:event_btSuperHumanoActionPerformed

    private void btHumanoFraquinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHumanoFraquinhoActionPerformed
        PessoaTransgenica pessoa = new PessoaTransgenica("esquisita", "muito baixa", 1.5);
        lbCor.setText(pessoa.getCor());
        lbOssos.setText(pessoa.getDensidadeOssea());
        lbPeso.setText(pessoa.getPesoMedio().toString());
    }//GEN-LAST:event_btHumanoFraquinhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAfro;
    private javax.swing.JButton btHumanoFraquinho;
    private javax.swing.JButton btOriental;
    private javax.swing.JButton btSuperHumano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbCor;
    private javax.swing.JLabel lbOssos;
    private javax.swing.JLabel lbPeso;
    // End of variables declaration//GEN-END:variables
}
