/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.atletas;

/**
 *
 * @author Aluno
 */
public class TelaAtletas extends javax.swing.JFrame {

    Atleta esportista;
    
    public TelaAtletas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNadador = new javax.swing.JButton();
        btLutadorKarate = new javax.swing.JButton();
        lbDescricao = new javax.swing.JLabel();
        btOQueEsseAtletaFaz = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btNadador.setText("Nadador");
        btNadador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNadadorActionPerformed(evt);
            }
        });

        btLutadorKarate.setText("Lutador de Karatê");
        btLutadorKarate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLutadorKarateActionPerformed(evt);
            }
        });

        lbDescricao.setText("-------------------------------------------------------");

        btOQueEsseAtletaFaz.setText("O que esse atleta faz?");
        btOQueEsseAtletaFaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOQueEsseAtletaFazActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btNadador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btLutadorKarate)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btOQueEsseAtletaFaz)
                    .addComponent(lbDescricao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNadador)
                    .addComponent(btLutadorKarate))
                .addGap(37, 37, 37)
                .addComponent(btOQueEsseAtletaFaz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDescricao)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOQueEsseAtletaFazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOQueEsseAtletaFazActionPerformed
        lbDescricao.setText(esportista.getPraticaEsportiva());
    }//GEN-LAST:event_btOQueEsseAtletaFazActionPerformed

    private void btNadadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNadadorActionPerformed
       esportista = new Nadador();
       
       Atleta lokao = new Atleta();
       lokao.getPraticaEsportiva();
    }//GEN-LAST:event_btNadadorActionPerformed

    private void btLutadorKarateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLutadorKarateActionPerformed
        esportista = new LutadorKarate();
    }//GEN-LAST:event_btLutadorKarateActionPerformed

        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtletas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLutadorKarate;
    private javax.swing.JButton btNadador;
    private javax.swing.JToggleButton btOQueEsseAtletaFaz;
    private javax.swing.JLabel lbDescricao;
    // End of variables declaration//GEN-END:variables
}
