/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.miniprojetinho;

/**
 *
 * @author hessinho
 */
public class simuladorFinanceiro extends javax.swing.JFrame {

    /**
     * Creates new form simuladorFinanceiro
     */
    public simuladorFinanceiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTextinho = new javax.swing.JLabel();
        lbEstacoes = new javax.swing.JLabel();
        tfEstacoes = new javax.swing.JTextField();
        lbTotensEstacoes = new javax.swing.JLabel();
        tfTotensEstacoes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btCalcular = new javax.swing.JButton();
        lbLinhas = new javax.swing.JLabel();
        tfLinhas = new javax.swing.JTextField();
        lbResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTextinho.setText("Faça seu orçamento!");

        lbEstacoes.setText("Estações");

        tfEstacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEstacoesActionPerformed(evt);
            }
        });

        lbTotensEstacoes.setText("Totens por estações");

        tfTotensEstacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotensEstacoesActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite a quantidade de:");

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        lbLinhas.setText("Linhas");

        tfLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLinhasActionPerformed(evt);
            }
        });

        lbResultado.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbTotensEstacoes)
                                    .addComponent(lbEstacoes)
                                    .addComponent(lbLinhas))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfEstacoes)
                                    .addComponent(tfTotensEstacoes)
                                    .addComponent(tfLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(lbTextinho)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(btCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lbResultado)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTextinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbLinhas)
                    .addComponent(tfLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstacoes)
                    .addComponent(tfEstacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotensEstacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotensEstacoes))
                .addGap(18, 18, 18)
                .addComponent(btCalcular)
                .addGap(28, 28, 28)
                .addComponent(lbResultado)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEstacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEstacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEstacoesActionPerformed

    private void tfTotensEstacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotensEstacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotensEstacoesActionPerformed

    private void tfLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLinhasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLinhasActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
           
        Integer linhas = Integer.valueOf(tfLinhas.getText());
        Integer estacoes = Integer.valueOf(tfEstacoes.getText());
        Integer totens = Integer.valueOf(tfTotensEstacoes.getText());
            
        Integer valorLinhas = 5000;
        Integer valorEstacoes = 500;
        Integer valorTotens = 250;
        
        Integer total = (linhas*valorLinhas) +
                        (estacoes*valorEstacoes) +
                        (totens * valorTotens);
            
        lbResultado.setText(String.format("O seu plano custará R$ %d", total));
        
    }//GEN-LAST:event_btCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simuladorFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simuladorFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simuladorFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simuladorFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simuladorFinanceiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbEstacoes;
    private javax.swing.JLabel lbLinhas;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbTextinho;
    private javax.swing.JLabel lbTotensEstacoes;
    private javax.swing.JTextField tfEstacoes;
    private javax.swing.JTextField tfLinhas;
    private javax.swing.JTextField tfTotensEstacoes;
    // End of variables declaration//GEN-END:variables
}
