/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.swing.encapsulamento;

/**
 *
 * @author hessinho
 */
public class TelaCarro extends javax.swing.JFrame {

    Carro carro1 = new Carro();
    Carro carro2 = new Carro();
    /**
     * Creates new form TelaCarro
     */
    public TelaCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLigar = new javax.swing.JButton();
        btAcelerar = new javax.swing.JButton();
        btFrear = new javax.swing.JButton();
        btDesligar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbVelocidade = new javax.swing.JLabel();
        pbVelocidade = new javax.swing.JProgressBar();
        btAcelerar2 = new javax.swing.JButton();
        btFrear2 = new javax.swing.JButton();
        btDesligar2 = new javax.swing.JButton();
        btLigar2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbStatus2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btLigar.setText("Ligar");
        btLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLigarActionPerformed(evt);
            }
        });

        btAcelerar.setText("Acelerar");
        btAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcelerarActionPerformed(evt);
            }
        });

        btFrear.setText("Freiar");
        btFrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFrearActionPerformed(evt);
            }
        });

        btDesligar.setText("Desligar");
        btDesligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesligarActionPerformed(evt);
            }
        });

        jLabel1.setText("status do Carro:");

        lbStatus.setForeground(new java.awt.Color(2, 163, 64));
        lbStatus.setText("Desligado");

        jLabel2.setText("Velocidade  atual (km/h):");

        lbVelocidade.setText("0");

        btAcelerar2.setText("Acelerar");
        btAcelerar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcelerar2ActionPerformed(evt);
            }
        });

        btFrear2.setText("Freiar");
        btFrear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFrear2ActionPerformed(evt);
            }
        });

        btDesligar2.setText("Desligar");
        btDesligar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesligar2ActionPerformed(evt);
            }
        });

        btLigar2.setText("Ligar");
        btLigar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLigar2ActionPerformed(evt);
            }
        });

        jLabel3.setText("status do Carro:");

        lbStatus2.setForeground(new java.awt.Color(2, 163, 64));
        lbStatus2.setText("Desligado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbStatus2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lbVelocidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btLigar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAcelerar)
                        .addGap(36, 36, 36)
                        .addComponent(btFrear)
                        .addGap(39, 39, 39)
                        .addComponent(btDesligar)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbStatus))
                            .addComponent(pbVelocidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btLigar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAcelerar2)
                                .addGap(36, 36, 36)
                                .addComponent(btFrear2)
                                .addGap(39, 39, 39)
                                .addComponent(btDesligar2)))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLigar)
                    .addComponent(btAcelerar)
                    .addComponent(btFrear)
                    .addComponent(btDesligar))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbVelocidade))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLigar2)
                    .addComponent(btAcelerar2)
                    .addComponent(btFrear2)
                    .addComponent(btDesligar2))
                .addGap(18, 18, 18)
                .addComponent(pbVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbStatus2))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcelerarActionPerformed
      carro1.acelerar();
        
        lbStatus.setText(carro1.getStatus());
        lbVelocidade.setText(carro1.getVelocidadeFormatada().toString());
    }//GEN-LAST:event_btAcelerarActionPerformed

    private void btDesligarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesligarActionPerformed
       carro1.desligar();
        
        lbStatus.setText(carro1.getStatus());
        lbVelocidade.setText(carro1.getVelocidadeFormatada().toString()); // TODO add your handling code here:
    }//GEN-LAST:event_btDesligarActionPerformed

    private void btLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLigarActionPerformed
        carro1.ligar();
        
        lbStatus.setText(carro1.getStatus());
        lbVelocidade.setText(carro1.getVelocidadeFormatada().toString());
    }//GEN-LAST:event_btLigarActionPerformed

    private void btFrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFrearActionPerformed
        carro1.frear();
        
        lbStatus.setText(carro1.getStatus());
        lbVelocidade.setText(carro1.getVelocidadeFormatada().toString());        // TODO add your handling code here:
    }//GEN-LAST:event_btFrearActionPerformed

    private void btAcelerar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcelerar2ActionPerformed
        carro2.acelerar();
        
        lbStatus2.setText(carro2.getStatus());
        pbVelocidade.setValue(carro2.getVelocidade().intValue());
    }//GEN-LAST:event_btAcelerar2ActionPerformed

    private void btFrear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFrear2ActionPerformed
        carro2.frear();
        
        lbStatus2.setText(carro2.getStatus());
        pbVelocidade.setValue(carro2.getVelocidade().intValue());
    }//GEN-LAST:event_btFrear2ActionPerformed

    private void btDesligar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesligar2ActionPerformed
        carro2.desligar();
        
        lbStatus2.setText(carro2.getStatus());
        pbVelocidade.setValue(carro2.getVelocidade().intValue());
    }//GEN-LAST:event_btDesligar2ActionPerformed

    private void btLigar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLigar2ActionPerformed
       carro2.ligar();
        
        lbStatus2.setText(carro2.getStatus());
        pbVelocidade.setValue(carro2.getVelocidade().intValue());
    }//GEN-LAST:event_btLigar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcelerar;
    private javax.swing.JButton btAcelerar2;
    private javax.swing.JButton btDesligar;
    private javax.swing.JButton btDesligar2;
    private javax.swing.JButton btFrear;
    private javax.swing.JButton btFrear2;
    private javax.swing.JButton btLigar;
    private javax.swing.JButton btLigar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbStatus2;
    private javax.swing.JLabel lbVelocidade;
    private javax.swing.JProgressBar pbVelocidade;
    // End of variables declaration//GEN-END:variables
}
