/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.swing.heranca;

/**
 *
 * @author Aluno
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btMaratonista = new javax.swing.JButton();
        lbVelocista = new javax.swing.JButton();
        btTriatleta = new javax.swing.JButton();
        lbFisico = new javax.swing.JLabel();
        lbTipoFisico = new javax.swing.JLabel();
        lbPerfomanceTela = new javax.swing.JLabel();
        lbPerformance = new javax.swing.JLabel();
        lbTempo = new javax.swing.JLabel();
        lbTempoMedioCorrendo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btMaratonista.setText("Nasce um maratonista");
        btMaratonista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaratonistaActionPerformed(evt);
            }
        });

        lbVelocista.setText("Nasce um velocista");
        lbVelocista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbVelocistaActionPerformed(evt);
            }
        });

        btTriatleta.setText("Nasce um Triatleta");
        btTriatleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTriatletaActionPerformed(evt);
            }
        });

        lbFisico.setText("tipo físico:");

        lbTipoFisico.setText("------");

        lbPerfomanceTela.setText("performance:");

        lbPerformance.setText("--------");

        lbTempo.setText("tempo médio correndo:");

        lbTempoMedioCorrendo.setText("--------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btMaratonista)
                    .addComponent(lbVelocista)
                    .addComponent(btTriatleta)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTipoFisico))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPerfomanceTela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPerformance))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTempoMedioCorrendo)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btMaratonista)
                .addGap(18, 18, 18)
                .addComponent(lbVelocista)
                .addGap(18, 18, 18)
                .addComponent(btTriatleta)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFisico)
                    .addComponent(lbTipoFisico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPerfomanceTela)
                    .addComponent(lbPerformance))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTempo)
                    .addComponent(lbTempoMedioCorrendo))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMaratonistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaratonistaActionPerformed
        Corredor maratonista = new Maratonista();
        
        lbFisico.setText(maratonista.getTipoFisico());
        lbPerformance.setText(maratonista.getPerformance());
        lbTempo.setText(maratonista.getTempoMedioCorrendo().toString());
    }//GEN-LAST:event_btMaratonistaActionPerformed

    private void lbVelocistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbVelocistaActionPerformed
      Corredor velocista = new Velocista();
        
        lbFisico.setText(velocista.getTipoFisico());
        lbPerformance.setText(velocista.getPerformance());
        lbTempo.setText(velocista.getTempoMedioCorrendo().toString());
    }//GEN-LAST:event_lbVelocistaActionPerformed

    private void btTriatletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTriatletaActionPerformed
       Corredor triatleta = new Velocista();
        
        lbFisico.setText(triatleta.getTipoFisico());
        lbPerformance.setText(triatleta.getPerformance());
        lbTempo.setText(triatleta.getTempoMedioCorrendo().toString());
    }//GEN-LAST:event_btTriatletaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMaratonista;
    private javax.swing.JButton btTriatleta;
    private javax.swing.JLabel lbFisico;
    private javax.swing.JLabel lbPerfomanceTela;
    private javax.swing.JLabel lbPerformance;
    private javax.swing.JLabel lbTempo;
    private javax.swing.JLabel lbTempoMedioCorrendo;
    private javax.swing.JLabel lbTipoFisico;
    private javax.swing.JButton lbVelocista;
    // End of variables declaration//GEN-END:variables
}
