/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.swing;

import java.awt.Color;

/**
 *
 * @author Aluno
 */
public class TelaComponentes extends javax.swing.JFrame {

    Integer cliques = 0;
    
    public TelaComponentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbProgresso = new javax.swing.JProgressBar();
        btProgressoAumentis = new javax.swing.JButton();
        btProgressoDiminuir = new javax.swing.JButton();
        btProgresso50 = new javax.swing.JButton();
        ckSolteiro = new javax.swing.JCheckBox();
        bdSolteiro = new javax.swing.JButton();
        lbCliques = new javax.swing.JLabel();
        btCliques = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pbProgresso.setForeground(new java.awt.Color(255, 102, 0));
        pbProgresso.setValue(20);

        btProgressoAumentis.setText("+");
        btProgressoAumentis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProgressoAumentisActionPerformed(evt);
            }
        });

        btProgressoDiminuir.setText("50%");
        btProgressoDiminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProgressoDiminuirActionPerformed(evt);
            }
        });

        btProgresso50.setText("-");
        btProgresso50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProgresso50ActionPerformed(evt);
            }
        });

        ckSolteiro.setText("Solteiro");
        ckSolteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSolteiroActionPerformed(evt);
            }
        });

        bdSolteiro.setText("Ver situação");
        bdSolteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdSolteiroActionPerformed(evt);
            }
        });

        lbCliques.setText("Quantos cliques: 0");

        btCliques.setText("Clica aqui!");
        btCliques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCliquesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckSolteiro)
                        .addGap(18, 18, 18)
                        .addComponent(bdSolteiro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btProgressoAumentis)
                        .addGap(18, 18, 18)
                        .addComponent(btProgresso50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btProgressoDiminuir))
                    .addComponent(pbProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCliques)
                    .addComponent(btCliques))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pbProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btProgresso50)
                    .addComponent(btProgressoAumentis)
                    .addComponent(btProgressoDiminuir))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckSolteiro)
                    .addComponent(bdSolteiro))
                .addGap(43, 43, 43)
                .addComponent(lbCliques)
                .addGap(18, 18, 18)
                .addComponent(btCliques)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btProgresso50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProgresso50ActionPerformed
       pbProgresso.setValue(pbProgresso.getValue() -5);
    }//GEN-LAST:event_btProgresso50ActionPerformed

    private void btProgressoDiminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProgressoDiminuirActionPerformed
        pbProgresso.setValue(50);
    }//GEN-LAST:event_btProgressoDiminuirActionPerformed

    private void btProgressoAumentisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProgressoAumentisActionPerformed
       pbProgresso.setValue(pbProgresso.getValue()+10);
    }//GEN-LAST:event_btProgressoAumentisActionPerformed

    private void ckSolteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSolteiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckSolteiroActionPerformed

    private void bdSolteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdSolteiroActionPerformed
        
        if(ckSolteiro.isSelected()){
            ckSolteiro.setForeground(Color.green);
        }else{
            ckSolteiro.setForeground(Color.red);
        }
    }//GEN-LAST:event_bdSolteiroActionPerformed

    private void btCliquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCliquesActionPerformed
            cliques++;
            
               lbCliques.setText("Quantos cliques: "+cliques);
    }//GEN-LAST:event_btCliquesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaComponentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdSolteiro;
    private javax.swing.JButton btCliques;
    private javax.swing.JButton btProgresso50;
    private javax.swing.JButton btProgressoAumentis;
    private javax.swing.JButton btProgressoDiminuir;
    private javax.swing.JCheckBox ckSolteiro;
    private javax.swing.JLabel lbCliques;
    private javax.swing.JProgressBar pbProgresso;
    // End of variables declaration//GEN-END:variables
}
